testserver :
	g++ -g -o testserver testserver.cc -L  /home/zwl/projects/cpp/projects_cpp/muduo/muduo_cpp11/lib -lmymuduo -lpthread -Wl,-rpath=/home/zwl/projects/cpp/projects_cpp/muduo/muduo_cpp11/lib -I  /home/zwl/projects/cpp/projects_cpp/muduo/muduo_cpp11 -std=c++11

clean :
	rm -f testserver